RPL-2: ENH - Added improvements
Batix/rundeck-ansible-plugin pull request #367
Opened 2024-04-26 14:28 UTC by alexander-variacode

Added improvements

2024-04-26 17:03 UTC, jtobard commented
I think it needs a little bit of info about the parameter, ideally in the same description. My doubts as a user who is just setting up the plugin or who already uses it and sees it appear in a new version would be:

1. Why does this new property exist?
2. When do I need to modify the default value?
3. What value should I put if I need to modify it?

2024-05-23 21:29 UTC, mrdubr requested changes
Looks good!
Some recommendations and a question about perf testing results.

2024-05-23 21:29 UTC, mrdubr commented on src/main/groovy/com/rundeck/plugins/ansible/plugin/AnsibleResourceModelSource.java
> +    ExecutorService executor = Executors.newFixedThreadPool(Integer.parseInt(numberThreads));
You should close the resource or use the `try-with-resources`

2024-05-23 21:29 UTC, mrdubr commented on src/main/groovy/com/rundeck/plugins/ansible/plugin/AnsibleResourceModelSource.java
> +    final Gson gson = new Gson();
Gson instances are Thread-safe so you can reuse them freely across multiple threads instead of creating a new one for every file

2024-05-23 21:29 UTC, mrdubr commented on src/main/groovy/com/rundeck/plugins/ansible/plugin/AnsibleResourceModelSource.java
> +  public void executeFutures(Stream<Path> directories, NodeSetImpl nodes) {
The term `Future` comes from the java "concurrent processing" domain and has little meaning in the context of this application. The method name tells us "how" things are being done instead of "what" is being done. That's a naming anti-pattern. In addition, I don't think there is a reason for this method to be public.

Suggestion:
`INodeSet getNodesFromDirectories(Stream<Path> directories)`

2024-05-23 21:29 UTC, mrdubr commented on src/main/groovy/com/rundeck/plugins/ansible/plugin/AnsibleResourceModelSource.java
> +    bufferedReader.close();
Won't get closed if line 463 throws an exception.

2024-05-23 21:29 UTC, mrdubr commented on src/main/groovy/com/rundeck/plugins/ansible/plugin/AnsibleResourceModelSource.java
> +    JsonElement json = new JsonParser().parse(bufferedReader);
Deprecated. No need to instantiate.

2024-05-23 21:29 UTC, mrdubr commented on src/main/groovy/com/rundeck/plugins/ansible/plugin/AnsibleResourceModelSource.java
> +      // for (String hostVar : root.keySet()) {
```suggestion
```

2024-05-23 21:29 UTC, mrdubr commented on src/main/groovy/com/rundeck/plugins/ansible/plugin/AnsibleResourceModelSource.java
> +    futures.stream().map(CompletableFuture::join).forEach(nodes::putNode);
AFAIU, with the calling thread blocked and a fixed thread pool of size 1, we would end up doing synchronous processing. 
I'm surprised to see your tests with a single thread showing perf improvements.
https://pagerduty.atlassian.net/browse/RUN-2366?focusedCommentId=747531
I might be missing something. Can you please elaborate?

2024-05-29 13:35 UTC, closed without merging

2024-05-29 13:35 UTC, alexander-variacode commented
This ticket is replaced by [ticket RUN-2451](https://pagerduty.atlassian.net/browse/RUN-2451) since it only improves time and resource usage by 20% compared to its replacement, which improves by 90%.